source 'https://rubygems.org'

gem 'bundler'
gem 'cucumber'
gem 'page-object'
gem 'parallel_tests'
gem 'rspec'
gem 'selenium-webdriver'
gem 'ffi'
gem 'rest-client'
gem 'activesupport', '~> 5.0.1'
gem 'dry-schema'
gem 'dry-validation'
gem 'colorize'
